# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TsApartment' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TsApartment

  pod 'IQKeyboardManager'
  pod 'AFNetworking', '~> 3.0'
  pod "JSONModel"
  pod "MJRefresh"
  #pod "AMap3DMap"
  pod "AMapLocation"
  pod "AMapSearch"
  pod "Masonry"
  pod 'SVProgressHUD'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod ’SDWebImage’
  

end
